import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Anime Waifu Compatibility Quiz",
  description:
    "Terms of service for the Anime Waifu/Husbando Personality Quiz. A fun fan project for entertainment purposes — results are not scientific.",
  alternates: {
    canonical: "https://www.animewaifucompatibility.xyz/terms",
  },
};

export default function Terms() {
  return (
    <div className="max-w-2xl mx-auto px-4 py-12 prose prose-gray">
      <h1>Terms of Service</h1>
      <p>Last updated: July 2026</p>

      <h2>Acceptance</h2>
      <p>By using Anime Match (&quot;the Site&quot;), you agree to these Terms of Service. If you do not agree, please do not use the Site.</p>

      <h2>Use of the Site</h2>
      <p>The Site is provided for <strong>entertainment purposes only</strong>. The personality quiz results are not scientific, guaranteed, or a reflection of real-world compatibility. They are generated by a simple algorithm for fun.</p>
      <ul>
        <li>You must be at least 13 years old to use the Site. If you are under 13, do not use the Site.</li>
        <li>No accounts, registration, or personal data submission is required.</li>
        <li>You agree not to misuse the Site (e.g., automated scraping, disrupting service, or uploading malicious content).</li>
      </ul>

      <h2>Intellectual Property</h2>
      <p>All character names, series titles, story elements, and related trademarks are the property of their respective owners. This is an unofficial fan project and is not affiliated with, endorsed by, or sponsored by any anime studio, publisher, or copyright holder. All character portrait images on this site are procedurally generated avatars, not official artwork.</p>
      <p>The quiz code, algorithm, site design, and original written descriptions (personality profiles, match reasons) are original work. You may not copy, redistribute, or commercially exploit the Site&apos;s content without permission.</p>

      <h2>Disclaimer</h2>
      <p>The Site is provided &quot;as is&quot; without warranties of any kind, express or implied. We make no guarantees about accuracy, availability, or fitness for a particular purpose. We are not responsible for any emotional reactions to quiz results — it&apos;s all in good fun!</p>

      <h2>Limitation of Liability</h2>
      <p>In no event shall the Site operators be liable for any damages arising from your use of the Site, including but not limited to direct, indirect, incidental, or consequential damages.</p>

      <h2>Third-Party Links</h2>
      <p>The Site may contain links to third-party websites (MyAnimeList, Crunchyroll, Google Forms). We are not responsible for the content or privacy practices of those sites.</p>

      <h2>Changes</h2>
      <p>We reserve the right to update these terms at any time. Continued use after changes constitutes acceptance of the new terms.</p>

      <h2>Contact</h2>
      <p>For questions about these terms: <strong>admin@animewaifuquiz.xyz</strong></p>
    </div>
  );
}
