// Anime recommendation database
// Each anime has personality affinity scores (-3 to +3 on each axis)
// Positive = matches outgoing/logical/playful/driven/loyal types
// Negative = matches introverted/emotional/serious/relaxed/independent types

export interface AnimeEntry {
  id: string;
  title: string;
  genre: string;
  year: number;
  episodes: number;
  imageUrl?: string;
  description: string;
  affinity: { e: number; l: number; v: number; p: number; n: number };
  tags: string[];
}

export const ANIME_LIST: AnimeEntry[] = [
  {
    id: "attack-on-titan",
    title: "Attack on Titan",
    genre: "Dark Fantasy / Action",
    year: 2013, episodes: 88,
    description: "Humanity fights for survival against man-eating Titans in a post-apocalyptic world. Intense, philosophical, and emotionally devastating.",
    affinity: { e: 0, l: 2, v: -1, p: 3, n: 2 },
    tags: ["Dark Fantasy", "Action", "Psychological", "Drama", "Military"],
  },
  {
    id: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    genre: "Action / Supernatural",
    year: 2020, episodes: 47,
    description: "A boy swallows a cursed finger and becomes host to the most powerful curse. Now he must train in Jujutsu sorcery to exorcise demons.",
    affinity: { e: 1, l: 1, v: 1, p: 3, n: 1 },
    tags: ["Action", "Supernatural", "Shonen", "Dark Fantasy", "School"],
  },
  {
    id: "demon-slayer",
    title: "Demon Slayer",
    genre: "Action / Adventure",
    year: 2019, episodes: 55,
    description: "After his family is slaughtered, Tanjiro sets out to become a demon slayer and find a cure for his demon-turned sister.",
    affinity: { e: 0, l: -2, v: -1, p: 2, n: 3 },
    tags: ["Action", "Adventure", "Shonen", "Historical", "Supernatural"],
  },
  {
    id: "naruto",
    title: "Naruto / Naruto Shippuden",
    genre: "Action / Adventure",
    year: 2002, episodes: 720,
    description: "A young ninja with a demon fox sealed inside him dreams of becoming the strongest ninja and leader of his village.",
    affinity: { e: 1, l: -1, v: 1, p: 3, n: 3 },
    tags: ["Action", "Adventure", "Shonen", "Martial Arts", "Friendship"],
  },
  {
    id: "one-piece",
    title: "One Piece",
    genre: "Adventure / Comedy",
    year: 1999, episodes: 1100,
    description: "Monkey D. Luffy sets sail with his pirate crew to find the legendary One Piece treasure and become the Pirate King.",
    affinity: { e: 3, l: -2, v: 3, p: 3, n: 3 },
    tags: ["Adventure", "Comedy", "Shonen", "Pirates", "Friendship"],
  },
  {
    id: "death-note",
    title: "Death Note",
    genre: "Psychological / Thriller",
    year: 2006, episodes: 37,
    description: "A genius high school student discovers a notebook that kills anyone whose name is written in it. A cat-and-mouse game with the world's greatest detective ensues.",
    affinity: { e: -1, l: 3, v: -2, p: 2, n: -2 },
    tags: ["Psychological", "Thriller", "Supernatural", "Detective", "Drama"],
  },
  {
    id: "fullmetal-alchemist",
    title: "Fullmetal Alchemist: Brotherhood",
    genre: "Action / Adventure",
    year: 2009, episodes: 64,
    description: "Two brothers search for the Philosopher's Stone to restore their bodies after a failed alchemical experiment. Deep themes of sacrifice and redemption.",
    affinity: { e: 0, l: 1, v: 0, p: 2, n: 2 },
    tags: ["Action", "Adventure", "Fantasy", "Drama", "Military"],
  },
  {
    id: "steins-gate",
    title: "Steins;Gate",
    genre: "Sci-Fi / Psychological",
    year: 2011, episodes: 24,
    description: "A self-proclaimed mad scientist accidentally invents a time machine and must grapple with the consequences of changing the past.",
    affinity: { e: -1, l: 3, v: 1, p: 1, n: 1 },
    tags: ["Sci-Fi", "Psychological", "Thriller", "Time Travel", "Drama"],
  },
  {
    id: "cowboy-bebop",
    title: "Cowboy Bebop",
    genre: "Sci-Fi / Noir",
    year: 1998, episodes: 26,
    description: "A ragtag crew of bounty hunters travel through space in their ship, the Bebop, each running from their past. Jazz-infused masterpiece.",
    affinity: { e: 0, l: 0, v: 1, p: -1, n: 0 },
    tags: ["Sci-Fi", "Noir", "Action", "Space", "Drama"],
  },
  {
    id: "spy-x-family",
    title: "Spy × Family",
    genre: "Comedy / Action",
    year: 2022, episodes: 37,
    description: "A spy, an assassin, and a telepath form a fake family for a mission, but genuine bonds begin to form. Wholesome and hilarious.",
    affinity: { e: 2, l: -1, v: 2, p: 1, n: 2 },
    tags: ["Comedy", "Action", "Slice of Life", "Spy", "Family"],
  },
  {
    id: "frieren",
    title: "Frieren: Beyond Journey's End",
    genre: "Fantasy / Drama",
    year: 2023, episodes: 28,
    description: "An elf mage reflects on the meaning of connection and time as she journeys to understand humans after her adventuring party grows old. Meditative and beautiful.",
    affinity: { e: -3, l: 0, v: 0, p: -1, n: 2 },
    tags: ["Fantasy", "Drama", "Adventure", "Slice of Life", "Philosophical"],
  },
  {
    id: "code-geass",
    title: "Code Geass",
    genre: "Mecha / Psychological",
    year: 2006, episodes: 50,
    description: "An exiled prince gains the power of absolute obedience and leads a rebellion against the empire that conquered his nation.",
    affinity: { e: 1, l: 3, v: 0, p: 3, n: -1 },
    tags: ["Mecha", "Psychological", "Military", "Supernatural", "Strategy"],
  },
  {
    id: "rezero",
    title: "Re:Zero",
    genre: "Dark Fantasy / Psychological",
    year: 2016, episodes: 50,
    description: "A boy is summoned to a fantasy world and discovers he has the power to return from death. He must endure endless suffering to save those he loves.",
    affinity: { e: -1, l: 1, v: 0, p: 2, n: 3 },
    tags: ["Dark Fantasy", "Psychological", "Drama", "Isekai", "Time Loop"],
  },
  {
    id: "my-hero-academia",
    title: "My Hero Academia",
    genre: "Action / School",
    year: 2016, episodes: 138,
    description: "In a world where 80% of people have superpowers, a quirkless boy dreams of becoming the greatest hero. Themes of legacy and self-sacrifice.",
    affinity: { e: 2, l: -1, v: 1, p: 3, n: 2 },
    tags: ["Action", "School", "Superhero", "Shonen", "Friendship"],
  },
  {
    id: "chainsaw-man",
    title: "Chainsaw Man",
    genre: "Action / Dark Comedy",
    year: 2022, episodes: 12,
    description: "A young man fused with a chainsaw devil becomes a devil hunter. Gory, unhinged, and surprisingly heartfelt. Pure chaotic energy.",
    affinity: { e: 2, l: 1, v: 2, p: 3, n: -1 },
    tags: ["Action", "Dark Comedy", "Supernatural", "Gore", "Seinen"],
  },
  {
    id: "your-name",
    title: "Your Name.",
    genre: "Romance / Drama",
    year: 2016, episodes: 1,
    description: "Two teenagers mysteriously swap bodies across time and space. A beautiful exploration of connection, fate, and longing. Visually stunning.",
    affinity: { e: 0, l: -3, v: 1, p: 0, n: 2 },
    tags: ["Romance", "Drama", "Supernatural", "Time Travel", "Movie"],
  },
  {
    id: "konosuba",
    title: "Konosuba",
    genre: "Comedy / Isekai",
    year: 2016, episodes: 20,
    description: "A boy dies and is reincarnated in a fantasy world with a useless goddess. The most hilarious parody of isekai anime ever made.",
    affinity: { e: 2, l: -1, v: 3, p: 0, n: 0 },
    tags: ["Comedy", "Isekai", "Fantasy", "Parody", "Adventure"],
  },
  {
    id: "violet-evergarden",
    title: "Violet Evergarden",
    genre: "Drama / Slice of Life",
    year: 2018, episodes: 13,
    description: "A former child soldier learns to understand emotions and love through her work as an Auto Memory Doll writing letters for others.",
    affinity: { e: -3, l: -2, v: -2, p: 0, n: 2 },
    tags: ["Drama", "Slice of Life", "Historical", "Emotional", "Healing"],
  },
  {
    id: "mob-psycho",
    title: "Mob Psycho 100",
    genre: "Action / Comedy",
    year: 2016, episodes: 37,
    description: "A shy boy with immense psychic powers learns that emotional growth matters more than supernatural strength. Stunning animation and deep themes.",
    affinity: { e: -2, l: -1, v: 0, p: 1, n: 2 },
    tags: ["Action", "Comedy", "Supernatural", "Slice of Life", "Psychological"],
  },
  {
    id: "kaguya-sama",
    title: "Kaguya-sama: Love Is War",
    genre: "Comedy / Romance",
    year: 2019, episodes: 37,
    description: "Two genius student council members engage in psychological warfare trying to make the other confess their love first. Brilliantly funny and clever.",
    affinity: { e: 0, l: 2, v: 1, p: 2, n: 1 },
    tags: ["Comedy", "Romance", "School", "Psychological", "Strategy"],
  },
  {
    id: "evangelion",
    title: "Neon Genesis Evangelion",
    genre: "Mecha / Psychological",
    year: 1995, episodes: 26,
    description: "Teenagers pilot giant bio-mecha to defend Earth from angels. A deconstruction of the mecha genre focusing on trauma, depression, and existential dread.",
    affinity: { e: -2, l: 2, v: -3, p: 1, n: -2 },
    tags: ["Mecha", "Psychological", "Drama", "Sci-Fi", "Dark"],
  },
  {
    id: "berserk",
    title: "Berserk",
    genre: "Dark Fantasy / Seinen",
    year: 1997, episodes: 25,
    description: "A lone mercenary with a giant sword battles demons in a medieval hellscape. The darkest, most brutal fantasy epic ever animated.",
    affinity: { e: -3, l: 0, v: -3, p: 3, n: -1 },
    tags: ["Dark Fantasy", "Seinen", "Action", "Medieval", "Tragedy"],
  },
  {
    id: "one-punch-man",
    title: "One Punch Man",
    genre: "Action / Comedy",
    year: 2015, episodes: 24,
    description: "A hero who can defeat any enemy with a single punch struggles with boredom and the search for a meaningful challenge.",
    affinity: { e: -1, l: 0, v: 1, p: 0, n: 0 },
    tags: ["Action", "Comedy", "Superhero", "Parody", "Seinen"],
  },
  {
    id: "toradora",
    title: "Toradora!",
    genre: "Romance / Comedy",
    year: 2008, episodes: 25,
    description: "Two high school students with crushes on each other's best friends team up to help each other pursue their loves. Classic rom-com with genuine heart.",
    affinity: { e: 1, l: -2, v: 1, p: 1, n: 2 },
    tags: ["Romance", "Comedy", "School", "Slice of Life", "Drama"],
  },
  {
    id: "mushoku-tensei",
    title: "Mushoku Tensei",
    genre: "Isekai / Adventure",
    year: 2021, episodes: 36,
    description: "A NEET reincarnates into a fantasy world and vows to live his second life without regrets. Gorgeous animation and mature themes.",
    affinity: { e: -1, l: 1, v: 1, p: 2, n: 1 },
    tags: ["Isekai", "Adventure", "Fantasy", "Drama", "Magic"],
  },
  {
    id: "horimiya",
    title: "Horimiya",
    genre: "Romance / Slice of Life",
    year: 2021, episodes: 13,
    description: "Popular girl meets quiet boy and they discover each other's hidden sides. Wholesome, realistic romance that skips the usual drama.",
    affinity: { e: 1, l: -2, v: 1, p: 0, n: 2 },
    tags: ["Romance", "Slice of Life", "School", "Comedy", "Drama"],
  },
  {
    id: "hunter-x-hunter",
    title: "Hunter × Hunter",
    genre: "Adventure / Action",
    year: 2011, episodes: 148,
    description: "A boy sets out to find his missing father by becoming a Hunter. Incredible power system, dark themes, and the best arc in shonen history.",
    affinity: { e: 1, l: 1, v: 1, p: 2, n: 2 },
    tags: ["Adventure", "Action", "Shonen", "Fantasy", "Strategy"],
  },
  {
    id: "clannad-after-story",
    title: "Clannad: After Story",
    genre: "Drama / Romance",
    year: 2008, episodes: 24,
    description: "The most emotionally devastating anime ever made. Follow the journey from high school to adulthood, marriage, and parenthood. Bring tissues.",
    affinity: { e: -1, l: -3, v: -1, p: 0, n: 3 },
    tags: ["Drama", "Romance", "Slice of Life", "School", "Family"],
  },
  {
    id: "made-in-abyss",
    title: "Made in Abyss",
    genre: "Adventure / Dark Fantasy",
    year: 2017, episodes: 13,
    description: "A girl and a robot boy descend into a mysterious abyss that holds ancient secrets. Beautiful on the surface, horrifying underneath.",
    affinity: { e: -1, l: 1, v: -1, p: 1, n: 2 },
    tags: ["Adventure", "Dark Fantasy", "Sci-Fi", "Mystery", "Drama"],
  },
  {
    id: "vinland-saga",
    title: "Vinland Saga",
    genre: "Historical / Action",
    year: 2019, episodes: 48,
    description: "A young Viking seeks revenge for his father's murder, but his journey becomes a deeper exploration of peace, purpose, and what it means to be free.",
    affinity: { e: -1, l: 2, v: -2, p: 2, n: 1 },
    tags: ["Historical", "Action", "Seinen", "Vikings", "Philosophical"],
  },
  {
    id: "girls-last-tour",
    title: "Girls' Last Tour",
    genre: "Slice of Life / Philosophical",
    year: 2017, episodes: 12,
    description: "Two girls travel through a post-apocalyptic wasteland in search of food and meaning. Surprisingly warm and deeply philosophical.",
    affinity: { e: -2, l: 0, v: 0, p: -2, n: 2 },
    tags: ["Slice of Life", "Philosophical", "Post-Apocalyptic", "Adventure", "Seinen"],
  },
  {
    id: "gurren-lagann",
    title: "Gurren Lagann",
    genre: "Action / Mecha",
    year: 2007, episodes: 27,
    description: "A boy with a drill-shaped soul inspires humanity to pierce the heavens. The most hype, motivational, and manly anime ever created.",
    affinity: { e: 3, l: -2, v: 3, p: 3, n: 2 },
    tags: ["Action", "Mecha", "Adventure", "Shonen", "Inspiring"],
  },
  {
    id: "your-lie-in-april",
    title: "Your Lie in April",
    genre: "Romance / Drama",
    year: 2014, episodes: 22,
    description: "A pianist who can no longer hear his own playing meets a free-spirited violinist who changes his world. Beautiful music, devastating emotions.",
    affinity: { e: 0, l: -3, v: 1, p: 1, n: 1 },
    tags: ["Romance", "Drama", "Music", "School", "Tragedy"],
  },
  {
    id: "monster",
    title: "Monster",
    genre: "Psychological / Thriller",
    year: 2004, episodes: 74,
    description: "A brilliant surgeon pursues a former patient who became a serial killer. A masterful slow-burn thriller about good, evil, and the spaces between.",
    affinity: { e: -2, l: 3, v: -3, p: 1, n: 0 },
    tags: ["Psychological", "Thriller", "Drama", "Mystery", "Seinen"],
  },
  {
    id: "fate-stay-night",
    title: "Fate/Stay Night: Unlimited Blade Works",
    genre: "Action / Fantasy",
    year: 2014, episodes: 26,
    description: "Seven mages summon legendary heroes to fight in a war for the Holy Grail. Stunning animation, philosophical themes, and epic battles.",
    affinity: { e: 0, l: 2, v: 0, p: 2, n: 1 },
    tags: ["Action", "Fantasy", "Supernatural", "Strategy", "Drama"],
  },
  {
    id: "puella-madoka",
    title: "Puella Magi Madoka Magica",
    genre: "Dark Fantasy / Psychological",
    year: 2011, episodes: 12,
    description: "A deconstruction of magical girl anime. What seems cute and hopeful becomes a dark exploration of sacrifice, despair, and hope. Absolutely essential viewing.",
    affinity: { e: -1, l: 1, v: -2, p: 1, n: 1 },
    tags: ["Dark Fantasy", "Psychological", "Magic", "Drama", "Tragedy"],
  },
  {
    id: "parasyte",
    title: "Parasyte: The Maxim",
    genre: "Horror / Sci-Fi",
    year: 2014, episodes: 24,
    description: "A boy's right hand is taken over by an alien parasite. They must coexist and fight other parasites. Themes of humanity, identity, and coexistence.",
    affinity: { e: -1, l: 2, v: -1, p: 2, n: 0 },
    tags: ["Horror", "Sci-Fi", "Action", "Psychological", "Seinen"],
  },
  {
    id: "bocchi-the-rock",
    title: "Bocchi the Rock!",
    genre: "Comedy / Music",
    year: 2022, episodes: 12,
    description: "An extreme social anxious girl joins a band and tries to overcome her fears through music. Relatable, hilarious, and surprisingly heartfelt.",
    affinity: { e: -3, l: -1, v: 2, p: 1, n: 1 },
    tags: ["Comedy", "Music", "Slice of Life", "School", "Anxiety"],
  },
  {
    id: "jujutsu-kaisen-0",
    title: "Jujutsu Kaisen 0",
    genre: "Action / Supernatural",
    year: 2021, episodes: 1,
    description: "Prequel film about Yuta Okkotsu, a boy cursed by his childhood friend's spirit. Heartbreaking origin story with incredible animation.",
    affinity: { e: -1, l: 1, v: -1, p: 2, n: 3 },
    tags: ["Action", "Supernatural", "Dark Fantasy", "Movie", "Tragedy"],
  },
  {
    id: "noragami",
    title: "Noragami",
    genre: "Action / Supernatural",
    year: 2014, episodes: 25,
    description: "A minor god without a single shrine seeks recognition while battling evil spirits. Themes of worth, connection, and what it means to matter.",
    affinity: { e: 1, l: 0, v: 1, p: 1, n: 2 },
    tags: ["Action", "Supernatural", "Comedy", "Shonen", "Mythology"],
  },
  {
    id: "classroom-of-the-elite",
    title: "Classroom of the Elite",
    genre: "Psychological / School",
    year: 2017, episodes: 25,
    description: "A class of students at an elite school are ranked and treated based on their performance. Cold calculation and social manipulation at its finest.",
    affinity: { e: -2, l: 3, v: -2, p: 2, n: -2 },
    tags: ["Psychological", "School", "Drama", "Strategy", "Seinen"],
  },
  {
    id: "kimetsu-no-yaiba",
    title: "Demon Slayer: Mugen Train",
    genre: "Action / Dark Fantasy",
    year: 2020, episodes: 1,
    description: "The highest-grossing anime film of all time. Tanjiro and friends board a mysterious train where dreams become nightmares. Rengoku's final stand.",
    affinity: { e: 0, l: -2, v: 0, p: 2, n: 3 },
    tags: ["Action", "Dark Fantasy", "Movie", "Shonen", "Tragedy"],
  },
  {
    id: "overlord",
    title: "Overlord",
    genre: "Dark Fantasy / Isekai",
    year: 2015, episodes: 52,
    description: "A player trapped in an MMORPG as his undead avatar builds a kingdom of monsters. Power fantasy from the villain's perspective.",
    affinity: { e: 0, l: 2, v: 0, p: 2, n: -1 },
    tags: ["Dark Fantasy", "Isekai", "Action", "Magic", "Strategy"],
  },
  {
    id: "dress-up-darling",
    title: "My Dress-Up Darling",
    genre: "Romance / Slice of Life",
    year: 2022, episodes: 12,
    description: "A shy craftsman and an energetic cosplayer collaborate on cosplay projects. The most wholesome and respectful romance in recent years.",
    affinity: { e: 2, l: -2, v: 2, p: 0, n: 1 },
    tags: ["Romance", "Slice of Life", "School", "Comedy", "Drama"],
  },
  {
    id: "dandadan",
    title: "Dandadan",
    genre: "Action / Comedy",
    year: 2024, episodes: 12,
    description: "A boy who believes in aliens and a girl who believes in ghosts team up to prove each other wrong. Chaotic, unhinged, and absolutely hilarious.",
    affinity: { e: 2, l: 0, v: 3, p: 2, n: 1 },
    tags: ["Action", "Comedy", "Supernatural", "Romance", "Shonen"],
  },
  {
    id: "solo-leveling",
    title: "Solo Leveling",
    genre: "Action / Fantasy",
    year: 2024, episodes: 12,
    description: "The weakest hunter of all time gains a unique leveling-up system and becomes the world's most powerful being. Pure satisfaction and stunning animation.",
    affinity: { e: -1, l: 1, v: -1, p: 3, n: -1 },
    tags: ["Action", "Fantasy", "Adventure", "Supernatural", "Shonen"],
  },
  {
    id: "oshi-no-ko",
    title: "Oshi no Ko",
    genre: "Drama / Supernatural",
    year: 2023, episodes: 11,
    description: "A doctor reincarnates as the child of his favorite idol. A brutal exposé of the entertainment industry's dark side. Incredible first episode.",
    affinity: { e: 0, l: 1, v: 1, p: 2, n: 0 },
    tags: ["Drama", "Supernatural", "Psychological", "Entertainment", "Mystery"],
  },
  {
    id: "heavenly-delusion",
    title: "Heavenly Delusion",
    genre: "Sci-Fi / Mystery",
    year: 2023, episodes: 13,
    description: "A pair of survivors travel through post-apocalyptic Japan searching for a place called Heaven. Beautiful, mysterious, and deeply unsettling.",
    affinity: { e: -1, l: 1, v: 0, p: 1, n: 2 },
    tags: ["Sci-Fi", "Mystery", "Adventure", "Post-Apocalyptic", "Seinen"],
  },
  {
    id: "frieren-recs",
    title: "Frieren (already listed)",
    genre: "Fantasy / Drama",
    year: 2023, episodes: 28,
    description: "Already in list — but worth mentioning again. A masterpiece about time, memory, and the bonds we form.",
    affinity: { e: -3, l: 0, v: 0, p: -1, n: 2 },
    tags: ["Fantasy", "Drama", "Adventure", "Philosophical", "Healing"],
  },
  {
    id: "apothecary-diaries",
    title: "The Apothecary Diaries",
    genre: "Mystery / Historical",
    year: 2023, episodes: 24,
    description: "A sharp-tongued apothecary solves medical mysteries in the imperial court. Brilliant protagonist, gorgeous setting, and clever writing.",
    affinity: { e: -1, l: 2, v: 0, p: 1, n: 0 },
    tags: ["Mystery", "Historical", "Drama", "Romance", "Medical"],
  },
  {
    id: "dungeon-meshi",
    title: "Delicious in Dungeon (Dungeon Meshi)",
    genre: "Fantasy / Comedy",
    year: 2024, episodes: 24,
    description: "A party of adventurers cooks and eats monsters they defeat in a dungeon. Surprisingly deep worldbuilding and genuinely funny.",
    affinity: { e: 1, l: 1, v: 2, p: 1, n: 2 },
    tags: ["Fantasy", "Comedy", "Adventure", "Cooking", "Seinen"],
  },
  {
    id: "cyberpunk-edgerunners",
    title: "Cyberpunk: Edgerunners",
    genre: "Sci-Fi / Action",
    year: 2022, episodes: 10,
    description: "A boy in Night City becomes an edgerunner to survive. Stunning animation, devastating story. One of the best anime of the decade.",
    affinity: { e: 1, l: 0, v: 1, p: 2, n: 1 },
    tags: ["Sci-Fi", "Action", "Drama", "Cyberpunk", "Tragedy"],
  },
  {
    id: "link-click",
    title: "Link Click",
    genre: "Mystery / Supernatural",
    year: 2021, episodes: 22,
    description: "Two men run a photo studio where they can dive into photos to change the past. Time travel rules, emotional stakes, and a banger soundtrack.",
    affinity: { e: -1, l: 2, v: 0, p: 1, n: 2 },
    tags: ["Mystery", "Supernatural", "Drama", "Time Travel", "Thriller"],
  },
  {
    id: "summer-time-rendering",
    title: "Summer Time Rendering",
    genre: "Mystery / Supernatural",
    year: 2022, episodes: 25,
    description: "A boy returns to his hometown for a funeral and gets caught in a time-loop mystery involving doppelgangers and ancient legends. Underrated masterpiece.",
    affinity: { e: -1, l: 2, v: -1, p: 2, n: 2 },
    tags: ["Mystery", "Supernatural", "Thriller", "Time Loop", "Shonen"],
  },
  {
    id: "86-eighty-six",
    title: "86: Eighty-Six",
    genre: "Mecha / Drama",
    year: 2021, episodes: 23,
    description: "A handler communicates with a squadron of soldiers from a discriminated minority fighting in remote mecha. Devastating war drama with incredible direction.",
    affinity: { e: -2, l: 1, v: -2, p: 2, n: 2 },
    tags: ["Mecha", "Drama", "Military", "Sci-Fi", "War"],
  },
];

export function getAnimeByPersonality(profile: { e: number; l: number; v: number; p: number; n: number }): { anime: AnimeEntry; score: number }[] {
  const scored = ANIME_LIST.map(anime => {
    // Calculate affinity score using weighted similarity
    const diff =
      Math.abs(profile.e - anime.affinity.e) * 1.0 +
      Math.abs(profile.l - anime.affinity.l) * 1.0 +
      Math.abs(profile.v - anime.affinity.v) * 1.2 +
      Math.abs(profile.p - anime.affinity.p) * 1.1 +
      Math.abs(profile.n - anime.affinity.n) * 1.3;
    
    const maxDiff = 6 * (1.0 + 1.0 + 1.2 + 1.1 + 1.3);
    const score = Math.round((1 - diff / maxDiff) * 100);
    
    return { anime, score: Math.max(0, Math.min(99, score)) };
  });

  return scored.sort((a, b) => b.score - a.score);
}
