// Personality Axes (each -3 to +3):
// E: Introvert(-3) → Extrovert(+3)
// L: Heart/Feeling(-3) → Head/Logic(+3)
// V: Serious(-3) → Playful(+3)
// P: Relaxed(-3) → Driven/Intense(+3)
// N: Independent(-3) → Loyal/Devoted(+3)

export interface Character {
  id: string;
  name: string;
  series: string;
  gender: "waifu" | "husbando";
  traits: { e: number; l: number; v: number; p: number; n: number };
  personality: string;
  description: string;
  matchReason: string;
  emoji: string;
  imageUrl?: string; // Publicly available character image URL
}

export const CHARACTERS: Character[] = [
  // ===== WAIFUS (FEMALE) =====
  {
    id: "hinata",
    name: "Hinata Hyuga",
    series: "Naruto",
    gender: "waifu",
    traits: { e: -2, l: -2, v: -1, p: -1, n: 3 },
    personality: "INFP — The Gentle Healer",
    description: "Quiet, kind-hearted, and fiercely loyal. Hinata is shy but has incredible inner strength when protecting those she loves.",
    matchReason: "You're gentle on the outside but strong when it counts. You value deep connections and would do anything for the people you love.",
    emoji: "💜",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b37-n1TJsAJ7jIvv.png",
  },
  {
    id: "mikasa",
    name: "Mikasa Ackerman",
    series: "Attack on Titan",
    gender: "waifu",
    traits: { e: -2, l: 2, v: -2, p: 2, n: 3 },
    personality: "ISTJ — The Silent Guardian",
    description: "Quiet, powerful, and unwavering. Mikasa speaks through her actions and protects with absolute dedication.",
    matchReason: "You're protective, loyal, and don't waste words. Your strength shows when the people you care about need you.",
    emoji: "⚔️",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b40881-F3gr1PkreDvj.png",
  },
  {
    id: "rem",
    name: "Rem",
    series: "Re:Zero",
    gender: "waifu",
    traits: { e: -1, l: -2, v: -1, p: 2, n: 3 },
    personality: "ISFJ — The Devoted Heart",
    description: "Hardworking, loyal, and self-sacrificing. Rem finds her purpose in serving others and will move mountains for those she believes in.",
    matchReason: "You're the kind of person who gives everything to the people you care about. Your loyalty is your superpower.",
    emoji: "🔵",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b88575-Ayu8UPDA8NS6.png",
  },
  {
    id: "yor",
    name: "Yor Forger",
    series: "Spy × Family",
    gender: "waifu",
    traits: { e: 0, l: -1, v: 0, p: 1, n: 2 },
    personality: "ESFP — The Secret Sweetheart",
    description: "Deadly assassin by night, caring mother by day. Yor is a contradiction — fierce yet gentle, clumsy yet precise.",
    matchReason: "You have two sides: soft and sweet with the people you love, but nobody messes with what's yours.",
    emoji: "💀",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b138102-ZOAu9jI2d5ke.png",
  },
  {
    id: "nobara",
    name: "Nobara Kugisaki",
    series: "Jujutsu Kaisen",
    gender: "waifu",
    traits: { e: 2, l: 1, v: 2, p: 2, n: 1 },
    personality: "ESTP — The Fearless Fighter",
    description: "Confident, bold, and unapologetically herself. Nobara knows her worth and isn't afraid to show it.",
    matchReason: "You're confident, don't take crap from anyone, and you know exactly who you are. That energy is magnetic.",
    emoji: "🔨",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b133700-f6sOO3TcgLV6.png",
  },
  {
    id: "shinobu",
    name: "Shinobu Kocho",
    series: "Demon Slayer",
    gender: "waifu",
    traits: { e: 0, l: 2, v: -1, p: 2, n: 2 },
    personality: "INTJ — The Elegant Strategist",
    description: "Calm, collected, and deadly intelligent. Shinobu hides a burning vengeance behind her eternal smile.",
    matchReason: "You're sharp, strategic, and keep your cool under pressure. People underestimate you — that's their mistake.",
    emoji: "🦋",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b136070-MC9LLxJsHyHE.png",
  },
  {
    id: "asuna",
    name: "Asuna Yuuki",
    series: "Sword Art Online",
    gender: "waifu",
    traits: { e: 1, l: 1, v: 0, p: 2, n: 3 },
    personality: "ENFJ — The Commander of Hearts",
    description: "Strong-willed, caring, and a natural leader. Asuna balances fierce determination with genuine warmth.",
    matchReason: "You're ambitious and capable, but you never lose your soft side. You lead with both strength and heart.",
    emoji: "⚔️",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b36828-j5ib0adAzGMx.png",
  },
  {
    id: "marin",
    name: "Marin Kitagawa",
    series: "My Dress-Up Darling",
    gender: "waifu",
    traits: { e: 3, l: -2, v: 3, p: 1, n: 1 },
    personality: "ESFP — The Vibrant Creator",
    description: "Energetic, passionate, and unapologetically enthusiastic. Marin chases what she loves with full force.",
    matchReason: "You're bubbly, passionate, and you inspire everyone around you. Your energy is contagious and people love being near you.",
    emoji: "❤️",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b133676-kV2czE3C8Qls.png",
  },
  {
    id: "frieren",
    name: "Frieren",
    series: "Frieren: Beyond Journey's End",
    gender: "waifu",
    traits: { e: -3, l: 0, v: 1, p: -1, n: 1 },
    personality: "INTP — The Timeless Philosopher",
    description: "Ancient, thoughtful, and surprisingly playful. Frieren views life through the lens of eternity, cherishing fleeting moments.",
    matchReason: "You're introspective and value deep connections. You understand that the best things in life are fleeting — and that's what makes them beautiful.",
    emoji: "✨",
  },
  {
    id: "boa",
    name: "Boa Hancock",
    series: "One Piece",
    gender: "waifu",
    traits: { e: 2, l: -1, v: 2, p: 2, n: 3 },
    personality: "ENFJ — The Pirate Empress",
    description: "Proud, beautiful, and completely devoted to love. Boa rules with absolute confidence but melts for the one she cherishes.",
    matchReason: "You have an unstoppable confidence that draws people in, but underneath it all, you're a romantic at heart.",
    emoji: "🐍",
  },
  {
    id: "rukia",
    name: "Rukia Kuchiki",
    series: "Bleach",
    gender: "waifu",
    traits: { e: -1, l: 1, v: 0, p: 1, n: 3 },
    personality: "ISTJ — The Steadfast Soul Reaper",
    description: "Dignified, responsible, and secretly caring. Rukia upholds tradition but isn't afraid to break rules for her friends.",
    matchReason: "You're responsible and dependable, but you have a playful side that comes out with the people you trust.",
    emoji: "❄️",
  },
  {
    id: "mitsuri",
    name: "Mitsuri Kanroji",
    series: "Demon Slayer",
    gender: "waifu",
    traits: { e: 2, l: -3, v: 2, p: 1, n: 1 },
    personality: "ENFP — The Love-Filled Warrior",
    description: "Gentle, loving, and surprisingly powerful. Mitsuri wants everyone to find love and happiness.",
    matchReason: "You're a hopeless romantic who believes in love and connection. Your warmth and strength together make you unforgettable.",
    emoji: "🌸",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b136072-xVwyRUKdpybi.png",
  },
  {
    id: "erza",
    name: "Erza Scarlet",
    series: "Fairy Tail",
    gender: "waifu",
    traits: { e: 2, l: 1, v: -1, p: 3, n: 3 },
    personality: "ESTJ — The Unwavering Knight",
    description: "The definition of strength and discipline. Erza leads with courage and would face an army alone for her friends.",
    matchReason: "You're a natural protector. Strong, disciplined, and utterly reliable. People look to you when things get tough.",
    emoji: "🛡️",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b5189-GR1xdok9SFsN.jpg",
  },
  {
    id: "makima",
    name: "Makima",
    series: "Chainsaw Man",
    gender: "waifu",
    traits: { e: 1, l: 3, v: -2, p: 3, n: -2 },
    personality: "ENTJ — The Master Manipulator",
    description: "Charismatic, calculating, and always several steps ahead. Makima commands absolute control with a serene smile.",
    matchReason: "You're ambitious, strategic, and you always know what you want. People are drawn to your confidence and vision.",
    emoji: "🐶",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b137080-UHcynYNjb5ZU.png",
  },
  {
    id: "kaguya",
    name: "Kaguya Shinomiya",
    series: "Kaguya-sama: Love Is War",
    gender: "waifu",
    traits: { e: -1, l: 2, v: 0, p: 2, n: 1 },
    personality: "INTJ — The Ice Princess Strategist",
    description: "Brilliant, proud, and emotionally repressed. Kaguya is a master of strategy but completely lost when it comes to love.",
    matchReason: "You're intelligent and composed, but deep down you just want someone who understands the real you.",
    emoji: "👑",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b120649-NPaWaIpWy60E.png",
  },
  {
    id: "chika",
    name: "Chika Fujiwara",
    series: "Kaguya-sama: Love Is War",
    gender: "waifu",
    traits: { e: 3, l: -2, v: 3, p: 0, n: 1 },
    personality: "ESFP — The Chaotic Fun-Bringer",
    description: "Bubbly, unpredictable, and utterly chaotic. Chika lives in her own world of fun and drags everyone along for the ride.",
    matchReason: "You're the life of the party. Your energy is absolutely infectious and you make everything more fun.",
    emoji: "🎵",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b121103-UGLxT8utLPnq.png",
  },
  {
    id: "mai",
    name: "Mai Sakurajima",
    series: "Rascal Does Not Dream of Bunny Girl Senpai",
    gender: "waifu",
    traits: { e: -1, l: 1, v: -1, p: 0, n: 2 },
    personality: "ISTP — The Cool Beauty",
    description: "Mature, witty, and refreshingly honest. Mai is a level-headed realist with a surprisingly playful teasing side.",
    matchReason: "You're sharp, witty, and you see through people's nonsense. Your sarcasm is a love language.",
    emoji: "🐰",
  },
  {
    id: "mitsuha",
    name: "Mitsuha Miyamizu",
    series: "Your Name.",
    gender: "waifu",
    traits: { e: 0, l: -2, v: 2, p: 0, n: 2 },
    personality: "ISFP — The Dreamer of Distant Stars",
    description: "Torn between tradition and freedom, Mitsuha longs for something more. She's restless, romantic, and deeply feeling.",
    matchReason: "You're a dreamer at heart. You feel everything deeply and believe in fate, connection, and the magic of the universe.",
    emoji: "🌌",
  },
  {
    id: "zero-two",
    name: "Zero Two",
    series: "Darling in the Franxx",
    gender: "waifu",
    traits: { e: 2, l: 0, v: 2, p: 3, n: 2 },
    personality: "ENFP — The Rebel Partner",
    description: "Wild, passionate, and desperate to be loved. Zero Two burns bright and fierce, searching for her one true partner.",
    matchReason: "You're intense, passionate, and you love with everything you have. You're looking for someone who completes you.",
    emoji: "👹",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b124381-pkTKi6HHNuVR.png",
  },
  {
    id: "yuno",
    name: "Yuno Gasai",
    series: "Future Diary",
    gender: "waifu",
    traits: { e: 1, l: -3, v: 1, p: 3, n: 3 },
    personality: "INFJ (Yandere) — The Obsessed Protector",
    description: "Sweet, loving, and absolutely terrifying. Yuno's love knows no bounds — including the boundaries of sanity.",
    matchReason: "When you love, you love completely. You'd go to the ends of the earth — and beyond — for the person you choose.",
    emoji: "🔪",
  },
  {
    id: "taiga",
    name: "Taiga Aisaka",
    series: "Toradora!",
    gender: "waifu",
    traits: { e: 1, l: -2, v: 2, p: 2, n: 2 },
    personality: "ESFP — The Palm-Top Tiger",
    description: "Small but fierce. Taiga is a tsundere through and through — prickly on the outside but soft and caring underneath.",
    matchReason: "You act tough but you're a softie at heart. You push people away but secretly hope they'll stay.",
    emoji: "🐯",
  },
  {
    id: "kurisu",
    name: "Kurisu Makise",
    series: "Steins;Gate",
    gender: "waifu",
    traits: { e: -1, l: 3, v: 0, p: 2, n: 1 },
    personality: "INTJ — The Reluctant Genius",
    description: "Brilliant scientist who hides her emotions behind logic. Kurisu is sharp, passionate about research, and secretly a tsundere.",
    matchReason: "You're brilliant and logical, but you have a hidden soft side. You value intelligence and deep conversation.",
    emoji: "⚡",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b34470-Jw2LXZBL5R8i.png",
  },
  {
    id: "megumin",
    name: "Megumin",
    series: "Konosuba",
    gender: "waifu",
    traits: { e: 0, l: -1, v: 3, p: 2, n: 1 },
    personality: "INFP — The Explosion Devotee",
    description: "Dramatic, passionate, and completely committed to her craft. Megumin lives for EXPLOSION magic and nothing else matters.",
    matchReason: "You're passionate about your niche interests and you don't care who knows it. Your enthusiasm is adorable and fierce.",
    emoji: "💥",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b89361-tq8PQQ4MmF0M.png",
  },
  {
    id: "violet",
    name: "Violet Evergarden",
    series: "Violet Evergarden",
    gender: "waifu",
    traits: { e: -3, l: 1, v: -3, p: -1, n: 3 },
    personality: "INFJ — The Doll Who Learned to Feel",
    description: "Once a weapon, now learning what love means. Violet's journey to understand human emotions is beautiful and heartbreaking.",
    matchReason: "You're deeply emotional but may struggle to express it. Your journey is one of learning to open your heart to others.",
    emoji: "🌹",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b90169-4wr1Zehnsac8.png",
  },
  {
    id: "power",
    name: "Power",
    series: "Chainsaw Man",
    gender: "waifu",
    traits: { e: 3, l: -2, v: 3, p: 3, n: -1 },
    personality: "ENTP — The Bloodthirsty Trickster",
    description: "Chaotic, unhinged, and completely self-serving. Power is a force of nature who says exactly what she thinks.",
    matchReason: "You're unapologetically yourself. chaotic, loud, and proud. Normal is boring — you're anything but.",
    emoji: "🩸",
  },
  {
    id: "yor-forger",
    name: "Holo",
    series: "Spice and Wolf",
    gender: "waifu",
    traits: { e: 1, l: 1, v: 2, p: -1, n: 2 },
    personality: "ENTP — The Wise Wolf",
    description: "Ancient, cunning, and playful. Holo is a harvest deity who loves good wine, clever banter, and warm company.",
    matchReason: "You're wise beyond your years but you never take life too seriously. You love witty conversations and creature comforts.",
    emoji: "🐺",
  },
  {
    id: "misato",
    name: "Misato Katsuragi",
    series: "Neon Genesis Evangelion",
    gender: "waifu",
    traits: { e: 2, l: 1, v: 1, p: 2, n: 1 },
    personality: "ESFP — The Fun-Loving Commander",
    description: "Party girl by night, tactical genius by day. Misato hides her deep trauma behind a carefree, drink-loving persona.",
    matchReason: "You're the life of the party, but you carry hidden depths. You know how to have fun and how to get serious when it counts.",
    emoji: "🍺",
  },
  {
    id: "revy",
    name: "Revy",
    series: "Black Lagoon",
    gender: "waifu",
    traits: { e: 1, l: 1, v: 1, p: 3, n: 1 },
    personality: "ESTP — The Two-Handed Devil",
    description: "Violent, vulgar, and gloriously unapologetic. Revy lives by her own code and answers to no one.",
    matchReason: "You don't follow rules — you make them. You're fierce, independent, and you take what you want from life.",
    emoji: "🔫",
  },
  {
    id: "yoruichi",
    name: "Yoruichi Shihouin",
    series: "Bleach",
    gender: "waifu",
    traits: { e: 2, l: 0, v: 2, p: 2, n: 2 },
    personality: "ESTP — The Flash Goddess",
    description: "Playful, powerful, and hiding depths of wisdom. Yoruichi can be a teasing cat or a deadly warrior in seconds.",
    matchReason: "You're playful and sharp, but you have a serious side that commands respect. You're never quite what people expect.",
    emoji: "🐱",
  },
  {
    id: "ochaco",
    name: "Ochaco Uraraka",
    series: "My Hero Academia",
    gender: "waifu",
    traits: { e: 2, l: -2, v: 2, p: 1, n: 2 },
    personality: "ENFP — The Cheerful Hero",
    description: "Sweet, determined, and endlessly optimistic. Ochaco wants to help people and make her family proud.",
    matchReason: "You're kind-hearted, optimistic, and driven by a desire to make the world better. You genuinely care about people.",
    emoji: "💖",
  },
  // ===== HUSBANDOS (MALE) =====
  {
    id: "levi",
    name: "Levi Ackerman",
    series: "Attack on Titan",
    gender: "husbando",
    traits: { e: -3, l: 2, v: -2, p: 2, n: 2 },
    personality: "ISTJ — The Cold Captain",
    description: "Cold, efficient, and absolutely the best at what he does. Levi's harsh exterior hides a deep care for his soldiers.",
    matchReason: "You're a perfectionist who expects the best from yourself and others. You show love through action, not words.",
    emoji: "🧹",
  },
  {
    id: "gojo",
    name: "Satoru Gojo",
    series: "Jujutsu Kaisen",
    gender: "husbando",
    traits: { e: 2, l: 2, v: 3, p: 2, n: -1 },
    personality: "ENTP — The Unstoppable Jester",
    description: "Playful, arrogant, and absurdly powerful. Gojo topples tradition while cracking jokes, because who can stop him?",
    matchReason: "You're confident, charismatic, and you refuse to take life too seriously — mostly because you know you've got this.",
    emoji: "🕶️",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b127691-9zqh1xpIubn7.png",
  },
  {
    id: "tanjiro",
    name: "Tanjiro Kamado",
    series: "Demon Slayer",
    gender: "husbando",
    traits: { e: 0, l: -3, v: -1, p: 2, n: 3 },
    personality: "ENFJ — The Kind-Hearted Slayer",
    description: "Gentle, empathetic, and impossibly kind. Tanjiro feels compassion even for demons, but fights with fierce determination.",
    matchReason: "Your empathy is your greatest strength. You see the good in everyone and fight for what matters with all your heart.",
    emoji: "🌊",
  },
  {
    id: "kakashi",
    name: "Kakashi Hatake",
    series: "Naruto",
    gender: "husbando",
    traits: { e: -2, l: 2, v: 1, p: 0, n: 2 },
    personality: "ISTP — The Laid-Back Genius",
    description: "Always late, always reading, always one step ahead. Kakashi is the strong, silent type with a hidden playful streak.",
    matchReason: "You're talented but humble, always reading or learning something new. You let your actions speak louder than words.",
    emoji: "📖",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b85-mkVBh2yjxjmx.png",
  },
  {
    id: "itachi",
    name: "Itachi Uchiha",
    series: "Naruto",
    gender: "husbando",
    traits: { e: -3, l: 2, v: -3, p: -1, n: 3 },
    personality: "INFJ — The Tragic Hero",
    description: "Calm, wise, and carrying an impossible burden. Itachi sacrificed everything for peace and his younger brother.",
    matchReason: "You're deeply thoughtful and carry more than people realize. You make sacrifices quietly because you believe in a greater good.",
    emoji: "👁️",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b14-9Kb1E5oel1ke.png",
  },
  {
    id: "lelouch",
    name: "Lelouch vi Britannia",
    series: "Code Geass",
    gender: "husbando",
    traits: { e: 1, l: 3, v: 0, p: 3, n: -1 },
    personality: "ENTJ — The Mastermind Emperor",
    description: "Brilliant, charismatic, and willing to become a villain for the greater good. Lelouch is the ultimate chess master.",
    matchReason: "You're incredibly strategic and always thinking five moves ahead. You'd do whatever it takes to achieve your vision.",
    emoji: "♟️",
  },
  {
    id: "kirito",
    name: "Kirito",
    series: "Sword Art Online",
    gender: "husbando",
    traits: { e: -2, l: 1, v: -1, p: 2, n: 3 },
    personality: "ISTJ — The Lone Black Swordsman",
    description: "Quiet, skilled, and fiercely protective. Kirito prefers solo play but becomes unstoppable when fighting for his friends.",
    matchReason: "You're independent and capable, but you open up completely to the people you trust. Your loyalty is absolute.",
    emoji: "⚫",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b36765-BnLbXg0Tzzh9.png",
  },
  {
    id: "roy",
    name: "Roy Mustang",
    series: "Fullmetal Alchemist",
    gender: "husbando",
    traits: { e: 2, l: 2, v: 1, p: 2, n: 2 },
    personality: "ENTJ — The Flame Alchemist",
    description: "Ambitious, charismatic, and seemingly lazy — until it matters. Roy plays the fool while climbing toward his goal of changing the world.",
    matchReason: "You're ambitious and strategic, but you know how to play the long game. People underestimate you — your favorite advantage.",
    emoji: "🔥",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b68-moBLY2WO2am3.png",
  },
  {
    id: "zoro",
    name: "Roronoa Zoro",
    series: "One Piece",
    gender: "husbando",
    traits: { e: -2, l: 1, v: -1, p: 2, n: 3 },
    personality: "ISTJ — The First Mate",
    description: "A man of few words and incredible ambition. Zoro's loyalty to his captain and his dream of becoming the world's best swordsman is absolute.",
    matchReason: "You're loyal to a fault and you never give up on your dreams. You'd follow your captain to the ends of the earth.",
    emoji: "⚔️",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b62-S7oAeA9WInjV.png",
  },
  {
    id: "luffy",
    name: "Monkey D. Luffy",
    series: "One Piece",
    gender: "husbando",
    traits: { e: 3, l: -2, v: 3, p: 3, n: 3 },
    personality: "ENFP — The Future Pirate King",
    description: "Goofy, fearless, and absolutely unstoppable. Luffy's simple philosophy: protect your friends and chase your dreams.",
    matchReason: "You're free-spirited, optimistic, and you never abandon your friends. Life is an adventure and you're here for all of it.",
    emoji: "🏴‍☠️",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b40-MNypXsxSRb1R.png",
  },
  {
    id: "bakugo",
    name: "Katsuki Bakugo",
    series: "My Hero Academia",
    gender: "husbando",
    traits: { e: 2, l: 1, v: 2, p: 3, n: 1 },
    personality: "ESTJ — The Explosive Ace",
    description: "Loud, proud, and explosively talented. Bakugo's abrasive exterior hides a deep drive to be the best hero possible.",
    matchReason: "You're competitive, driven, and you don't hide your intensity. Your passion comes across loud and clear — and that's powerful.",
    emoji: "💥",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b88892-bdOha3lNcaN6.png",
  },
  {
    id: "todoroki",
    name: "Shoto Todoroki",
    series: "My Hero Academia",
    gender: "husbando",
    traits: { e: -2, l: 1, v: -2, p: 0, n: 1 },
    personality: "INFJ — The Ice and Fire Prince",
    description: "Stoic, conflicted, and coming into his own. Todoroki learns to accept both sides of himself — his fire and his ice.",
    matchReason: "You're coming to terms with who you are. You have different sides to your personality and you're learning to embrace them all.",
    emoji: "❄️🔥",
  },
  {
    id: "sasuke",
    name: "Sasuke Uchiha",
    series: "Naruto",
    gender: "husbando",
    traits: { e: -3, l: 2, v: -2, p: 2, n: -1 },
    personality: "INTJ — The Avenger",
    description: "Brooding, talented, and driven by vengeance. Sasuke's cold exterior hides a heart that's been broken and a path of redemption.",
    matchReason: "You keep people at a distance, but you're on a personal journey of growth. You're not the same person you were yesterday.",
    emoji: "🌩️",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b13-SISLEw1oAD7a.png",
  },
  {
    id: "l",
    name: "L (Ryuzaki)",
    series: "Death Note",
    gender: "husbando",
    traits: { e: -3, l: 3, v: 0, p: 1, n: 0 },
    personality: "INTP — The World's Greatest Detective",
    description: "Eccentric, brilliant, and socially awkward. L lives in a world of pure logic, solving crimes with unorthodox methods.",
    matchReason: "You're an eccentric genius who operates differently from everyone else. You see patterns others miss.",
    emoji: "🍰",
  },
  {
    id: "light",
    name: "Light Yagami",
    series: "Death Note",
    gender: "husbando",
    traits: { e: 1, l: 3, v: 0, p: 3, n: -2 },
    personality: "ENTJ — The God of the New World",
    description: "Perfect student, brilliant strategist, and slowly corrupted by absolute power. Light believes he alone can reshape the world.",
    matchReason: "You have a strong sense of justice — and the intelligence to back it up. But be careful: power changes people.",
    emoji: "📓",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b80-26EhwSsSqQ50.png",
  },
  {
    id: "rengoku",
    name: "Kyojuro Rengoku",
    series: "Demon Slayer",
    gender: "husbando",
    traits: { e: 3, l: -1, v: 2, p: 3, n: 3 },
    personality: "ENFJ — The Blazing Heart",
    description: "Passionate, loud, and endlessly encouraging. Rengoku believed in doing what's right with burning conviction.",
    matchReason: "You're passionate and encouraging, lifting everyone around you. Your spirit is infectious and you live life with purpose.",
    emoji: "🔥",
  },
  {
    id: "eren",
    name: "Eren Yeager",
    series: "Attack on Titan",
    gender: "husbando",
    traits: { e: 0, l: 1, v: -1, p: 3, n: 3 },
    personality: "INFJ — The Freedom Seeker",
    description: "Born fighting for freedom, Eren transforms from angry boy to determined revolutionary. His conviction is absolute.",
    matchReason: "You believe in freedom above all else. You'd fight against any cage, real or metaphorical, that holds you or your loved ones back.",
    emoji: "🐦",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b40882-dsj7IP943WFF.jpg",
  },
  {
    id: "spike",
    name: "Spike Spiegel",
    series: "Cowboy Bebop",
    gender: "husbando",
    traits: { e: 0, l: 0, v: 2, p: -1, n: 1 },
    personality: "ISTP — The Cool Bounty Hunter",
    description: "Laid-back, stylish, and haunted by his past. Spike drifts through space with his crew, fighting and philosophizing.",
    matchReason: "You're effortlessly cool and take life as it comes. You have a past that shaped you, but you keep moving forward.",
    emoji: "🎷",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b1-ChxaldmieFlQ.png",
  },
  {
    id: "okabe",
    name: "Okabe Rintarou",
    series: "Steins;Gate",
    gender: "husbando",
    traits: { e: 1, l: 1, v: 2, p: 1, n: 2 },
    personality: "ENFP — The Mad Scientist",
    description: "Eccentric, dramatic, and secretly brilliant. Okabe plays the fool to hide his genius and his pain.",
    matchReason: "You're a little weird and totally okay with it. Your quirks are what make you brilliant. El Psy Kongroo.",
    emoji: "🧪",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b35252-DY9TW6pusqeh.png",
  },
  {
    id: "shoto",
    name: "Kamina",
    series: "Gurren Lagann",
    gender: "husbando",
    traits: { e: 3, l: -2, v: 3, p: 3, n: 2 },
    personality: "ENFP — The Unstoppable Badass",
    description: "Believes in you when you don't believe in yourself. Kamina is the hype man we all need — bold, loud, and inspiring.",
    matchReason: "You're the friend who pushes others to be their best. Your confidence lifts everyone around you. 'Believe in me who believes in you!'",
    emoji: "🔥",
  },
  {
    id: "genos",
    name: "Genos",
    series: "One Punch Man",
    gender: "husbando",
    traits: { e: -2, l: 2, v: -2, p: 2, n: 3 },
    personality: "ISTJ — The Cyborg Devotee",
    description: "Serious, dedicated, and constantly seeking strength. Genos is completely devoted to his master and his mission.",
    matchReason: "You're dedicated and serious about your goals. You respect those stronger than you and you're always striving to improve.",
    emoji: "🤖",
  },
  {
    id: "guts",
    name: "Guts",
    series: "Berserk",
    gender: "husbando",
    traits: { e: -3, l: 0, v: -3, p: 3, n: -1 },
    personality: "ISTP — The Struggler",
    description: "A survivor forged in hell. Guts fights against impossible odds with sheer will, a massive sword, and a broken but unbroken spirit.",
    matchReason: "You've been through more than most can imagine, but you keep fighting. Your will is iron, and you don't know how to give up.",
    emoji: "⚔️",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b422-XTaiTuvRohsV.png",
  },
  {
    id: "jotaro",
    name: "Jotaro Kujo",
    series: "JoJo's Bizarre Adventure",
    gender: "husbando",
    traits: { e: -2, l: 2, v: -1, p: 1, n: 2 },
    personality: "ISTP — The Stoic Stand User",
    description: "Cool, quiet, and devastatingly effective. Jotaro says little but commands respect with every action.",
    matchReason: "You're the strong, silent type. You don't need to prove anything — your actions speak volumes. ORA.",
    emoji: "🃏",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b4003-gWDSEGbeOAll.png",
  },
  {
    id: "saitama",
    name: "Saitama",
    series: "One Punch Man",
    gender: "husbando",
    traits: { e: -2, l: 0, v: 0, p: -1, n: 0 },
    personality: "ISTP — The Hero for Fun",
    description: "Overpowered and underwhelmed. Saitama is a hero who finds everything boring because he can end any fight with one punch.",
    matchReason: "You're incredibly capable but humble about it. You don't seek recognition — you just want to live a simple life and help people.",
    emoji: "👊",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/b73935-ON5d0mAcrItd.jpg",
  },
  {
    id: "araragi",
    name: "Koyomi Araragi",
    series: "Monogatari",
    gender: "husbando",
    traits: { e: -1, l: -1, v: 1, p: 0, n: 2 },
    personality: "ENFP — The Selfless Helper",
    description: "Willing to sacrifice himself for any girl in need. Araragi is selfless to a fault, always getting involved in supernatural trouble.",
    matchReason: "You can't help but get involved when someone needs help — even if it costs you. Your heart is too big for your own good.",
    emoji: "🦇",
  },
  {
    id: "shigeo",
    name: "Shigeo Kageyama (Mob)",
    series: "Mob Psycho 100",
    gender: "husbando",
    traits: { e: -3, l: -2, v: -1, p: 0, n: 2 },
    personality: "INFP — The Quiet Power",
    description: "Shy, kind, and holding back incredible power. Mob's journey is about emotional growth, not just psychic strength.",
    matchReason: "You're quiet and humble, but you have incredible depths. Your kindness is your greatest power — never lose it.",
    emoji: "🌀",
  },
  {
    id: "reigen",
    name: "Arataka Reigen",
    series: "Mob Psycho 100",
    gender: "husbando",
    traits: { e: 2, l: 2, v: 2, p: 0, n: 2 },
    personality: "ENFJ — The Silver-Tongued Mentor",
    description: "Con artist by trade, mentor by heart. Reigen has no psychic powers but unlimited charisma and genuine care for Mob.",
    matchReason: "You're charismatic and know how to talk your way through anything. But underneath the bluster, you genuinely care.",
    emoji: "💼",
  },
  {
    id: "vash",
    name: "Vash the Stampede",
    series: "Trigun",
    gender: "husbando",
    traits: { e: 2, l: -2, v: 2, p: -1, n: 2 },
    personality: "ENFP — The Pacifist Gunslinger",
    description: "Silly goofball who never kills, hiding the deadliest gunslinger in the universe. Vash believes in love and peace against all odds.",
    matchReason: "You believe in the best in people, even when the world gives you reasons not to. You're a pacifist with the heart of a hero.",
    emoji: "🌻",
  },
  {
    id: "alucard",
    name: "Alucard",
    series: "Hellsing",
    gender: "husbando",
    traits: { e: 1, l: 2, v: 1, p: 3, n: -1 },
    personality: "ENTP — The Undying Monster",
    description: "Arrogant, sadistic, and absurdly powerful. Alucard has lived for centuries and is utterly bored until he finds worthy opponents.",
    matchReason: "You're powerful, confident, and perhaps a little scary. But you choose to use your strength in service of a cause.",
    emoji: "🧛",
    imageUrl: "https://s4.anilist.co/file/anilistcdn/character/large/n601-CVySkaFQgsPW.jpg",
  },
  {
    id: "howl",
    name: "Howl Jenkins Pendragon",
    series: "Howl's Moving Castle",
    gender: "husbando",
    traits: { e: 0, l: -1, v: 2, p: 1, n: 1 },
    personality: "ENFP — The Dashing Wizard",
    description: "Vain, dramatic, and secretly insecure. Howl hides his vulnerabilities behind charm, magic, and fabulous hair.",
    matchReason: "You're charming and creative, but you have hidden depths. You're more than the persona you show the world.",
    emoji: "🏰",
  },
  {
    id: "sebastian",
    name: "Sebastian Michaelis",
    series: "Black Butler",
    gender: "husbando",
    traits: { e: 1, l: 3, v: 0, p: 1, n: -1 },
    personality: "ENTJ — The Devilish Butler",
    description: "Perfect, elegant, and utterly inhuman. Sebastian serves his young master with flawless skill and a sinister agenda.",
    matchReason: "You're elegant, capable, and always in control. But something dark and ambitious lurks beneath the surface.",
    emoji: "🍽️",
  },
  {
    id: "cloud",
    name: "Cloud Strife",
    series: "Final Fantasy VII",
    gender: "husbando",
    traits: { e: -2, l: 1, v: -1, p: 1, n: 1 },
    personality: "ISTP — The Ex-SOLDIER",
    description: "Brooding, mysterious, and carrying a fractured past. Cloud pretends to be cool and aloof while hiding deep trauma.",
    matchReason: "You're the strong, silent type with a complicated past. You're on a journey of self-discovery and learning who you really are.",
    emoji: "⚔️",
  },
  {
    id: "gilgamesh",
    name: "Gilgamesh",
    series: "Fate/Stay Night",
    gender: "husbando",
    traits: { e: 2, l: 2, v: 1, p: 3, n: -3 },
    personality: "ENTJ — The King of Heroes",
    description: "Arrogant beyond measure, yet his power backs up every word. Gilgamesh sees everything as his treasure — including you.",
    matchReason: "You know your worth and you're not afraid to show it. You demand the best because you know you deserve it.",
    emoji: "👑",
  },
  {
    id: "joker",
    name: "Ren Amamiya (Joker)",
    series: "Persona 5",
    gender: "husbando",
    traits: { e: -1, l: 1, v: 1, p: 1, n: 2 },
    personality: "ENFJ — The Phantom Trickster",
    description: "A rebel with a cause, leading a team of outcasts to change corrupt hearts. Cool, capable, and fiercely loyal to his found family.",
    matchReason: "You stand up for the oppressed and fight against injustice. Your friends are your family and you'd steal the world for them.",
    emoji: "🎭",
  },
];

export function getCharactersByGender(gender: "waifu" | "husbando" | "both"): Character[] {
  if (gender === "both") return CHARACTERS;
  return CHARACTERS.filter(c => c.gender === gender);
}
